
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - revive
    - gocyclo
    - gocognit
    - govet
    - staticcheck
    - gosimple
    - unused
    - typecheck
    - ineffassign
    - gofmt
    - misspell
    - maintidx 

linters-settings:
  gocyclo:
    min-complexity: 10
  revive:
    rules:
      - name: line-length-limit
        arguments: [120]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0