REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM admin_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM employee_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM user_role;
DROP ROLE IF EXISTS admin_role;
DROP ROLE IF EXISTS employee_role;
DROP ROLE IF EXISTS user_role;



