DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Artwork_event;
DROP TABLE IF EXISTS TicketPurchases;
DROP TABLE IF EXISTS Artwork;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Collection;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Admins;







