services:
  test-runner:
    container_name: test_runner_artworks
    build:
      context: ../
      dockerfile: ./cmd/test/Dockerfile
    env_file:
      - ../configs/db.env
    depends_on:
      postgres:
        condition: service_healthy
    # working_dir: /app
    command: tail -f /dev/null # Просто держим контейнер alive
    networks:
      - test-network

  postgres:
    container_name: test_postgres_artworks
    hostname: postgres
    image: postgres:14.8-alpine3.18
    env_file:
      - ../configs/db.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - test-network
  
  migrator:
    container_name: test_migrator_artworks
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - ../configs/db.env
    build:
      context: ../migrations
      dockerfile: Dockerfile
    networks:
      - test-network


volumes:
  pg-db-volume:
    driver: local

networks:
  test-network:
    driver: bridge
