# docker compose -f ./deployment/docker-compose.ci.yml --env-file ./configs/test_db.env up --build -d  postgres migrator
# go test -v github.com/CakeForKit/artworksDB.git/internal/tests/integration
# docker compose -f ./deployment/docker-compose.ci.yml --env-file ./configs/test_db.env run --rm test-runner go test -v github.com/CakeForKit/artworksDB.git/internal/tests/integration
services:
  test-runner:
    container_name: test_runner_artworks
    build:
      context: ../
      dockerfile: ./cmd/test/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      # redis_artworks:
      #   condition: service_healthy

    # command: tail -f /dev/null # Просто держим контейнер alive
    environment:
      - POSTGRES_HOST=test_postgres_artworks
      - GIN_MODE=debug
      - AIR_WATCH=.  # Следить за изменениями во всей директории
    volumes:
      - ../:/app          # Монтируем весь проект в контейнер
      - /app/go/pkg/mod   # Кэш для модулей Go
      - /app/bin          # Для бинарников (если нужно)
    command: air -c ./cmd/test/.air.toml  # Заменяем стандартную команду на air

    networks:
      - test-network
      - redis_artworks

  postgres:
    container_name: test_postgres_artworks
    hostname: postgres
    image: postgres:14.8-alpine3.18
    env_file:
      - ../configs/test_db.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - test-network
  
  migrator:
    container_name: test_migrator_artworks
    depends_on:
      postgres:
        condition: service_healthy  
    env_file:
      - ../configs/test_db.env
    environment:
      - POSTGRES_HOST=test_postgres_artworks
    build:
      context: ../migrations
      dockerfile: Dockerfile
    networks:
      - test-network

  redis_artworks:
    container_name: redis_artworks
    hostname: redis_artworks
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    env_file:
      - ../configs/redis.env
    networks:
      - redis_artworks


volumes:
  pg-db-volume:
    driver: local

networks:
  test-network:
    driver: bridge
  redis_artworks:
    name: redis_artworks
