FROM golang:1.25.1-alpine

RUN apk add git bash && \
    go install github.com/swaggo/swag/cmd/swag@latest && \
    go install github.com/a-h/templ/cmd/templ@v0.3.865
RUN go install github.com/air-verse/air@latest

# RUN go env -w GOPROXY=https://proxy.golang.org,direct && \
#     go env -w GOSUMDB=off

WORKDIR /app

COPY ./go.* .
RUN go mod download
COPY . .
RUN mkdir -p tmp
CMD ["air", "-c", "./cmd/app/.air.toml"]
# COPY ./cmd/app/.air.toml .
# CMD ["air", "-c", ".air.toml"]