app:
  token_symmetric_key: "12345678901234567890123456789012"
  access_token_duration: "15h"
  buy_ticket_transaction_duration: "15m"
  port: 8080

datebase:
  max_open_conns: 10      # Максимальное количество открытых соединений
  max_idle_conns: 5       # Mаксимальное число одновременно активных соединений с БД
  conn_max_lifetime: "1h" # Как долго соединение может оставаться в пуле

