-- Active: 1748883456071@@127.0.0.1@8123@artworks
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Artwork_event;
DROP TABLE IF EXISTS TicketPurchases;
DROP TABLE IF EXISTS Artworks;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Collection;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS tickets_user;
DROP TABLE IF EXISTS TicketPurchases;






