// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/artworks": {
            "get": {
                "description": "Retrieves a list of all artworks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artworks"
                ],
                "summary": "Get all artworks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ArtworkResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ArtworkResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/models.AuthorResponse"
                },
                "collection": {
                    "$ref": "#/definitions/models.CollectionResponse"
                },
                "creationYear": {
                    "type": "integer",
                    "example": 1503
                },
                "id": {
                    "type": "string",
                    "example": "bb2e8400-e29b-41d4-a716-446655442222"
                },
                "material": {
                    "type": "string",
                    "example": "Poplar wood"
                },
                "size": {
                    "type": "string",
                    "example": "77 cm × 53 cm"
                },
                "technic": {
                    "type": "string",
                    "example": "Oil painting"
                },
                "title": {
                    "type": "string",
                    "example": "Mona Lisa"
                }
            }
        },
        "models.AuthorResponse": {
            "type": "object",
            "properties": {
                "birthYear": {
                    "type": "integer",
                    "example": 1452
                },
                "deathYear": {
                    "type": "integer",
                    "example": 1519
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Leonardo da Vinci"
                }
            }
        },
        "models.CollectionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "aa1e8400-e29b-41d4-a716-446655441111"
                },
                "title": {
                    "type": "string",
                    "example": "Louvre Museum Collection"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Artworks",
	Description:      "API для системы учета произведений искусств",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
