name: Tests

on:
  push:
    branches: [ "*" ]

# -tags=integration

jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.25'
  #       cache-dependency-path: go.sum
  #   - name: Run Unit Tests
  #     run: |
  #       go test -shuffle=on git.iu7.bmstu.ru/ped22u691/PPO.git/internal/services/userservice;
  #     env:
  #       ALLURE_OUTPUT_DIR: allure-results
  #       ALLURE_OUTPUT_PATH: ${{ github.workspace }}
  #     # go test -v -shuffle=on git.iu7.bmstu.ru/ped22u691/PPO.git/internal/services/... 

  #   - name: Upload Allure results
  #     if: always()
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: allure-results-unit  # Название артефакта
  #       path: allure-results  # Путь к файлам отчета

  integration-e2e-tests:
    runs-on: ubuntu-latest
    # needs: unit-tests # CHANGE
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create test_db.env file
        run: |
          echo "POSTGRES_HOST=localhost" > ./configs/test_db.env
          echo "POSTGRES_DB=artworks" >> ./configs/test_db.env
          echo "POSTGRES_PORT=5432" >> ./configs/test_db.env
          echo "POSTGRES_USER=puser" >> ./configs/test_db.env
          echo "POSTGRES_PASSWORD=ppassword" >> ./configs/test_db.env

      - name: Build and up db and migrator containers
        run: |
          docker compose -f ./deployment/docker-compose.ci.yml \
            --env-file ./configs/test_db.env up --build -d postgres migrator
        env:
          POSTGRES_HOST: localhost

      - name: Run Integration Tests
        id: integration-tests
        run: go test -v -shuffle=on git.iu7.bmstu.ru/ped22u691/PPO.git/internal/tests/integration 
        env:
          ALLURE_OUTPUT_DIR: allure-results
          ALLURE_OUTPUT_PATH: ${{ github.workspace }}

      - name: Upload Integration Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-integration  # Название артефакта
          path: allure-results  # Путь к файлам отчета

      - name: Build and up test-runner container
        id: test-runner-up
        if: steps.integration-tests.outcome == 'success'
        run: |
          docker compose -f ./deployment/docker-compose.ci.yml \
            --env-file ./configs/test_db.env up --build -d redis_artworks test-runner 
      
      - name: Run E2E Tests
        if: steps.test-runner-up.outcome == 'success'
        run: |
          docker compose -f ./deployment/docker-compose.ci.yml --env-file ./configs/test_db.env \
            exec \
            -e ALLURE_OUTPUT_PATH=/app \
            -T test-runner \
            go test ./internal/tests/e2e/e2e_api
          docker cp test_runner_artworks:/app/allure-results ${{ github.workspace }}/allure-results-e2e || true
          ls -la ${{ github.workspace }}/allure-results-e2e
        env:
          ALLURE_OUTPUT_DIR: allure-results
          ALLURE_OUTPUT_PATH: /app

      - name: Check directories
        if: always()
        run: |
          echo "=== Directory structure ==="
          ls -la
          ls -la ./allure-results
          ls -la ./allure-results-e2e

      - name: Upload E2E Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-e2e  # Название артефакта
          path: allure-results-e2e  # Путь к файлам отчета

      - name: Cleanup
        if: always()
        run: |
          docker compose -f ./deployment/docker-compose.ci.yml \
            down -v --remove-orphans

      
  allure-report:
    if: always() 
    needs: [ integration-e2e-tests ]
    # needs: [ unit-tests, integration-e2e-tests ]    # CHANGE
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository  # Клонируем репозиторий, включая ветку gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Операции будем выполнять в ветке gh-pages
          path: gh-pages  # Клонируем файлы в папку gh-pages

      - name: Check directories
        if: always()
        run: |
          echo "=== Directory structure ==="
          ls -la
          echo "=== allure-results-integration ==="
          ls -la allure-results-integration/ || echo "Not found"
          echo "=== allure-results-e2e ==="
          ls -la allure-results-e2e/ || echo "Not found"

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*  # Загружаем все артефакты, начинающиеся с "allure-results-"
          path: allure-results/      # Загружаем в одну папку
          merge-multiple: true       # Объединяем файлы из разных артефактов

      - name: Allure Report action from marketplace  # Генерация отчета Allure
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: allure-results  # Папка с результатами тестов
          allure_history: allure-history  # Папка для хранения истории отчетов

      - name: Deploy report to Github Pages  # Публикация отчета на GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию
          publish_branch: gh-pages  # Публикуем отчет в ветку gh-pages
          publish_dir: allure-history  # Папка, где находится сгенерированный отчет


        