name: Integration Test 

on:
  push:
    branches: [ "*" ]

# -tags=integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          echo "Current directory: $(pwd)"
          docker compose -f ./deployment/docker-compose.ci.yml \
            --env-file ./configs/db.env build
          docker ps

      - name: Run Integration Tests
        run: |
          echo "Current directory: $(pwd)"
          docker compose -f ./deployment/docker-compose.ci.yml \
            --env-file ./configs/db.env \
            run --rm test-runner \
            go test -v -shuffle=on git.iu7.bmstu.ru/ped22u691/PPO.git/internal/services/... 

      - name: Cleanup
        if: always()
        run: docker compose down -v --remove-orphans

        